[project]
name = "forecasting-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
   "pandas",
   "xgboost",
   "scikit-learn",
   "matplotlib"
]

[dependency-groups]
dev = [
    "ipython>=9.2.0",
]
